---
# This file holds the config given to Tenks when running `tenks.sh`. It
# assumes the existence of the bridge `breth1`.

node_types:
  type0:
    memory_mb: 1024
    vcpus: 1
    volumes:
      # There is a minimum disk space capacity requirement of 4GiB when using Ironic Python Agent:
      # https://github.com/openstack/ironic-python-agent/blob/master/ironic_python_agent/utils.py#L290
      - capacity: 4GiB
    physical_networks:
      - physnet1
    console_log_enabled: true

specs:
  - type: type0
    count: 2
    ironic_config:
      resource_class: test-rc
      network_interface: noop
      # Ansible's os_ironic module sets silly defaults if you don't provide
      # them.
      properties:
        cpus: 1
        cpu_arch: "x86_64"
        memory_mb: 1024
        local_gb: 4

nova_flavors: []

physnet_mappings:
  physnet1: "{{ bridge_interface }}"

bridge_interface: "{{ lookup('env', 'INTERFACE') | default('breth1', true) }}"
ipxe_ip: "{{ hostvars[inventory_hostname]['ansible_' ~ bridge_interface | replace('-', '_')].ipv4.address }}"
deploy_kernel: "http://{{ ipxe_ip }}:8089/ironic-agent.kernel"
deploy_ramdisk: "http://{{ ipxe_ip }}:8089/ironic-agent.initramfs"

# No placement service.
wait_for_placement: false
